### ISSUE TITLE
【bug提交】技能【传教】不会消耗手牌

### ISSUE THREAD

**Issue by ccxx2c2** [bianjingshiyi/TouhouTrek#11]
版本：19.11.1
正常效果：使用技能后，被选中的牌自动从手牌中打出
现在效果：仍然保留在手牌中，且可以二次打出
触发条件：选择对应角色，使用对应技能

**Comment by ccxx2c2** [comment]
实际上，所有的技能都只调用了doeffect函数，没有调用”丢掉卡片“的函数。

**Comment by bianjingshiyi** [comment]
已修复，需要编写测试。

**Comment by ccxx2c2** [comment]
传教修了，出警没修
（。。。
