### ISSUE TITLE
被扣置的事件牌方向有误

### ISSUE THREAD

**Issue by ccxx2c2** [bianjingshiyi/TouhouTrek#15]
版本：19.11.1
正常效果：被扣的事件牌，被新的牌顶出去后，应该发动正面效果
现在效果：发动的是负面效果
触发方法：扣置事件区有牌。
补充：无论这之前的事件牌是正面还是负面发动，被顶出去的牌都是发动的负面效果

**Comment by ccxx2c2** [comment]
版本：19.11.4
现在效果：直接崩溃（报argumentOutOfRangeException.

**Comment by bianjingshiyi** [comment]
尝试修复了19.11.1中存在的问题，EventCard被重构了，DoEffect不需要再调用UseCard.UseEventCard，可以直接编写卡片效果。另外连锁事件不需要在效果中将其加入连锁区。
