### ISSUE TITLE
社团主催的“合同招募”技能无法正常使用

### ISSUE THREAD

**Issue by kounoshiryu** [bianjingshiyi/TouhouTrek#16]
该技能使用的时候可以选择手牌，但无法正常打出，既不会产生任何效果，手牌也不会被消费，无论是否选定对象，该技能都无法将手牌视作“约稿“打出

**Comment by ccxx2c2** [comment]
记得参考wiki写bug：https://github.com/bianjingshiyi/TouhouTrek/wiki
另：这个无法使用是已知的，参见https://github.com/bianjingshiyi/TouhouTrek/wiki/process
