### ISSUE TITLE
【bug提交】选中事件卡结束回合会导致弃牌环节无法进行

### ISSUE THREAD

**Issue by kounoshiryu** [bianjingshiyi/TouhouTrek#17]
![image](https://user-images.githubusercontent.com/57258034/68026633-3d736e80-fceb-11e9-93df-2012f19495b7.png)

版本：19.11.1
正常效果：手牌因超过上限而被选择弃牌
现在效果：无法弃牌，也无法进入下一回合
触发方法：选中事件卡并结束回合且手牌数超过上限时

**Comment by kounoshiryu** [comment]
![image](https://user-images.githubusercontent.com/57258034/68026815-b5da2f80-fceb-11e9-9e27-98734f6a90e6.png)
追加截图

**Comment by ccxx2c2** [comment]
复现成功
