### ISSUE TITLE
【开发优化】建议将没有实现的功能用特别方式标出

### ISSUE THREAD

**Issue by ccxx2c2** [bianjingshiyi/TouhouTrek#8]
优化优势：没实现就不要装作实现了（
目前状态：与已实现功能颜色、形式完全相同，无任何变化
建议方法或描述：如在没实现的弃牌堆区写上-1等不可实现的字、更改颜色灰度、打上叉等等；在已实现的功能如行动牌的说明文字上，写上跟哇噶我格啊嘎嘎来填充。
当前状态：就是没区别（

**Comment by bianjingshiyi** [comment]
需要更具体的补充。

**Comment by ccxx2c2** [comment]
基本解决了。
